# Generated by Django 3.2 on 2023-09-26 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('password', models.CharField(max_length=100)),
                ('access_token', models.CharField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('password', models.CharField(max_length=100)),
                ('access_token', models.CharField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('password', models.CharField(max_length=100)),
                ('access_token', models.CharField(max_length=3000)),
            ],
        ),
    ]
