# Generated by Django 3.2 on 2023-09-26 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0003_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('abb', models.CharField(max_length=10)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.grade')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.manager')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.teacher')),
            ],
        ),
    ]
