# Generated by Django 3.2 on 2023-09-27 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0005_auto_20230927_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='abb',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
