# Generated by Django 3.2 on 2023-09-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20230927_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='question_set',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
